Apply patch `st-dracula-0.8.2.diff`
The `st-dracula-0.8.2.diff` conflicted with the `st-alpha-0.8.2.diff`
patch when trying to `git apply`, so this is a diff that resolves that
conflict.

The error recieved when trying to apply the original patch:

```
error: patch failed: config.def.h:84
error: config.def.h: patch does not apply
```